### ISSUE TITLE
Release for cyclonedx-node-pnpm

### ISSUE THREAD

**Issue by ThuF** [CycloneDX/cyclonedx-node-pnpm#5]
Is there a released version that could be used for pnpm projects?

If not is it possible to use the tool somehow to generate SBOM for a pnpm project?

**Comment by jkowalleck** [comment]
as the readme states: 
> this project is in early development stage

feel free contributing to the project to bring it to a release

**Comment by jkowalleck** [comment]
see some work here: https://github.com/CycloneDX/cyclonedx-node-npm/discussions/811#discussion-5300848
